# Generated by Django 6.0.1 on 2026-08-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbusinessprofile',
            name='business_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
