# Generated by Django 6.0.1 on 2026-05-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usersubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='tier',
            field=models.CharField(choices=[('COMMUNITY', 'Community'), ('INDIVIDUAL', 'Individual'), ('ENTERPRISE', 'Enterprise')], default='COMMUNITY', max_length=20),
        ),
    ]
