# Generated by Django 6.0.1 on 2026-05-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_usersubscription_tier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbusinessprofile',
            name='default_currency',
        ),
        migrations.AddField(
            model_name='userbusinessprofile',
            name='currency',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='userbusinessprofile',
            name='business_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userbusinessprofile',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
