### GET Invoice

GET {{base_url}}/demo-invoices/ HTTP/1.1
Content-Type: application/json


### Retirve Invoice

GET {{base_url}}/demo-invoices/31/ HTTP/1.1
Content-Type: application/json


### POST Inovice

POST {{base_url}}/demo-invoices/ HTTP/1.1
Content-Type: application/json

{
  "invoice_number": "001",
  "items": [
    {
      "id": 200,
      "title": "Logo"
    },
    {
      "title": "Social Media Poster"
    }
  ],
  "name": "Noufal",
  "payments": [
    {
      "amount": "10"
    }
  ]
}


### Update Inovice

PUT {{base_url}}/demo-invoices/31/ HTTP/1.1
Content-Type: application/json

{
  "invoice_number": "001",
  "items": [
    {
      "id": 133,
      "title": "Logo D"
    },
    {
      "id": 117,
      "title": "SMP"
    },
    {
      "title": "id cardz"
    }
  ],
  "name": "Mohammed Noufal",
  "payments": [
    {
      "amount": "288",
      "id": 77
    }
  ]
}


### Update Inovice

PATCH {{base_url}}/demo-invoices/18/ HTTP/1.1
Content-Type: application/json

{
  "invoice_number": "001",
  "items": [
    {
      "title": "Logo Dark"
    },
    {
      "title": "SMP z"
    }
  ],
  "name": "Mohammed Noufal KA",
  "payments": [
    {
      "amount": "230"
    }
  ]
}
