# Generated by Django 6.0.1 on 2026-08-16 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='template',
            field=models.CharField(default='classic', max_length=20),
        ),
    ]
