# Generated by Django 6.0.1 on 2026-08-28 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_invoice_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='business_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
