# Generated by Django 6.0.1 on 2026-07-24 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('document_type', models.CharField(choices=[('TERMS', 'Terms and Conditions'), ('PRIVACY', 'Privacy Policy')], max_length=20)),
                ('version', models.CharField(max_length=10)),
                ('content', models.TextField()),
                ('effective_date', models.DateField()),
            ],
            options={
                'ordering': ['-effective_date', '-created_at'],
                'unique_together': {('document_type', 'version')},
            },
        ),
        migrations.CreateModel(
            name='UserLegalDocumentAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('legal_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_acceptances', to='legal.legaldocument')),
            ],
        ),
    ]
