# Generated by Django 6.0.1 on 2026-06-07 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0002_userpolicyacceptance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLegalDocumentAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('legal_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_acceptances', to='legal.legaldocument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_document_acceptances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'legal_document')},
            },
        ),
        migrations.DeleteModel(
            name='UserPolicyAcceptance',
        ),
    ]
