### Check field exist

GET {{base_url}}/users/check-user/?field=username&value=test2
Content-Type: application/json


### Check referral code exist

GET {{base_url}}/users/check-referral-code/?code
Content-Type: application/json

### Change Password

POST {{base_url}}/users/change-password/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "current_password": "noufalka123",
  "new_password": "weak"
}


### Reset Password

POST {{base_url}}/users/reset-password/ HTTP/1.1
Content-Type: application/json

{
  "email": "noufal@email.com",
  "new_password": "noufal123"
}


### Delete Account

DELETE {{base_url}}/users/profile/delete/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "refresh": "{{refresh}}"
}
