### Signup

POST {{base_url}}/users/signup/ HTTP/1.1
Content-Type: application/json

{
  "email": "test3@email.com",
  "full_name": "Test3",
  "password": "noufal123",
  "platform": "mobile",
  "referral_code_input": "NOUFAL",
  "username": "test4"
}

> {%
  var cookieHeader = response.headers.valueOf("Set-Cookie");

  if (cookieHeader) {
      var match = cookieHeader.match(/access_token=([^;]+)/);

      if (match) {
          client.global.set("token", match[1]);
      }
  }
  else{
      client.global.set("token", response.body.access)
    }
%}


### Login

POST {{base_url}}/users/login/ HTTP/1.1
Content-Type: application/json

{
  "email": "test@email.com",
  "password": "noufal123",
  "platform": "mobile"
}

> {%
  var cookieHeader = response.headers.valueOf("Set-Cookie");

  if (cookieHeader) {
      var match = cookieHeader.match(/access_token=([^;]+)/);

      if (match) {
          client.global.set("token", match[1]);
      }
  }
  else{
      client.global.set("token", response.body.access)
      client.global.set("refresh", response.body.refresh)
    }
%}


### Logout

POST {{base_url}}/users/logout/ HTTP/1.1
Content-Type: application/json

{
  "refresh": "{{refresh}}"
}


