### GET Clients

GET {{base_url}}/clients/?is_archived=true HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


### GET Client

GET {{base_url}}/clients/anu/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

> {%

  client.global.set("client_slug", response.body.slug )

%}


### GET Clients Usage

GET {{base_url}}/clients/usage/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


### POST Client

POST {{base_url}}/clients/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "address": "idukki",
  "email": "anu@email.com",
  "name": "anu",
  "phone": "9746469318"
}


### PATCH Client

PATCH {{base_url}}/clients/{{client_slug}}/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "is_archived": false
}


### DELETE Client

DELETE {{base_url}}/clients/{{client_slug}}/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
