### GET Clients

GET {{base_url}}/clients/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


### GET Client

GET {{base_url}}/clients/mohammed-18/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

> {%

  client.global.set("client_slug", response.body.slug )

%}


### GET Clients Usage

GET {{base_url}}/clients/usage/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


### POST Client

POST {{base_url}}/clients/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "address": "Madavana",
  "email": "mohammed@email.com",
  "name": "Mohammed Client",
  "phone": "9746469318"
}


### PATCH Client

PATCH {{base_url}}/clients/{{client_slug}}/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "is_active": true
}


### DELETE Client

DELETE {{base_url}}/clients/{{client_slug}}/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
