### GET Tags

GET {{base_url}}/tags/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


### GET Tag

GET {{base_url}}/tags/1/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
