# Generated by Django 6.0.1 on 2026-05-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_is_active_client_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
