### GET Invoices

GET {{base_url}}/invoices/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


### GET Invoices

GET {{base_url}}/invoices/?from_issue_date=2026-05-01&to_issue_date=2026-05-31 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


### GET Invoice

GET {{base_url}}/invoices/1/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


### POST Invoices

POST {{base_url}}/invoices/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Test Client",
  "email": "test@example.com",
  "phone": "+919876543210",
  "currency": "INR",
  "status": "DRAFT",
  "items": [
    {"title": "Test Item", "quantity": "1", "unit_price": "150.00", "unit_type": "QTY"}
  ],
  "payments": []
}


### PUT Invoices

PUT {{base_url}}/invoices/1/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "client": 2,
  "discount": "600",
  "due_date": "2026-05-28",
  "issue_date": "2026-05-21",
  "items": [
    {
      "product": 1,
      "quantity":2
    },
    {
      "product": 4
    }
  ],
  "payments": [
    {
      "amount": "100.00",
      "payment_date": "2026-05-21"
    },
    {
      "amount": "200.00",
      "payment_date": "2026-05-22"
    },
    {
      "amount": "200.00",
      "payment_date": "2026-05-22"
    },
    {
      "amount": "2800.00",
      "payment_date": "2026-05-22"
    }
  ]
}


### DELETE Inovice

DELETE {{base_url}}/invoices/23/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
