### GET Products

GET {{base_url}}/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


### Retrive Product

GET {{base_url}}/products/social-media-poster-2/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

> {%

  client.global.set("product_slug", response.body.slug )

%}


### GET Product Usage

GET {{base_url}}/products/usage/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


### POST Product

POST {{base_url}}/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Social Media Poster",
  "unit_price": "500"
}


### PATCH Product

PATCH {{base_url}}/products/{{product_slug}}/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Social Media",
}



### DELETE Product

DELETE {{base_url}}/products/{{product_slug}}/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


