# Generated by Django 6.0.1 on 2026-05-20 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_invoice_invoiceitem_paymentrecord_delete_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
