# Generated by Django 6.0.1 on 2026-05-30 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_alter_invoice_name_alter_invoiceitem_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrecord',
            name='invoice',
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='PaymentRecord',
        ),
    ]
